version: "3"

tasks:
  default:
    cmds:
      - task -l

  build:
    desc: Render all Quarto outputs
    cmds:
      - quarto render --to html --to pdf --to epub

  clean:
    desc: Clean generated files
    cmds:
      - quarto clean

  preview:
    desc: Preview site locally
    cmds:
      - quarto preview
